### ISSUE TITLE
MongoDB error in production

### ISSUE THREAD

**Issue by mattwells19** [lvl-mattwells/DevsPlayingPoker#83]
Getting a 500 when trying to make a request that hits Mongo:
```
Error: MongoError: {"topologyVersion":{"processId":"63bf74f38c7b6966598be053","counter":4},"ok":0,"errmsg":"not primary","code":10107,"codeName":"NotWritablePrimary","$clusterTime":{"clusterTime":{"$timestamp":"7187595145284419629"},"signature":{"hash":"MKbtK7fQJI0tVzqpU+SqHJrjD+8=","keyId":{"_bsontype":"Long","high":1659467109,"low":54,"unsigned":false}}},"operationTime":{"$timestamp":"7187595145284419629"}}
    at WireProtocol.commandSingle (https://deno.land/x/mongo@v0.30.1/src/protocol/protocol.ts:49:13)
    at async Collection.insertMany (https://deno.land/x/mongo@v0.30.1/src/collection/collection.ts:181:17)
    at async Collection.insertOne (https://deno.land/x/mongo@v0.30.1/src/collection/collection.ts:149:29)
    at async handleCookie (file:///usr/app/middlewares/cookies.ts:33:21)
    at async Layer.handle [as handle_request] (https://deno.land/x/opine@2.2.0/src/router/layer.ts:76:5)
```

I think it's just throwing in the `handleCookie` middleware since that's the first MongoDB call on a request. Not really sure what's happening, tbh. Might have something to do with how we're connecting to the Atlas DB. Needs more investigation.

**Comment by mattwells19** [comment]
Earlier when the issue was first reported I was able to restart the app and it started working again. Not sure what caused it to reappear.

**Comment by lvl-mattwells** [comment]
This error isn't showing up in Deno Deploy staging environments and doesn't show up when connecting to the Atlas cluster locally. It seems to only be an issue in production with Fly.io.

Not sure what the differences are between Fly and Deno Deploy are... Maybe need to reset the `DB_URL` secret in Fly to make sure it's correct? According to Mongo's docs (and what I was able to get working locally), the URI needs to have the format:
`mongodb+srv://<username>:<password>@<atlas_url>/<db>?authMechanism=SCRAM-SHA-1`.

Obviously can't compare that to the existing secrets in Fly and Deno Deploy so maybe we just reset it so we know the format is "correct" and see what happens?

**Comment by lvl-mattwells** [comment]
Updated DB_URL in Deno Deploy and Fly and merged the mentioned PR to support the new format. Leaving the issue open to monitor the status of the fix.
